;[]-----------------------------------------------------------------[]
;|      N_SCOPY.ASM -- near struct copy routine                      |
;[]-----------------------------------------------------------------[]

;
;       C/C++ Run Time Library - Version 5.0
; 
;       Copyright (c) 1987, 1992 by Borland International
;       All Rights Reserved.
; 

; calls to this routine are generated by the compiler to copy
; one "struct" value to another
;
; On entry:
;
;       CX      = Number of bytes to copy

_Text SEGMENT BYTE PUBLIC USE16 'CODE'
    public N_SCOPY@
    N_SCOPY@ proc near
        push    bp
        mov     bp,sp
        push    si
        push    di
        push    ds
        lds     si, [bp+4]
        les     di, [bp+8]
        cld
        shr     cx, 1
        rep     movsw
        adc     cx, cx
        rep     movsb
        pop     ds
        pop     di
        pop     si
        pop     bp
        ret     8
    N_SCOPY@ endp
_TEXT ends

end